# Generated by Django 5.2.6 on 2026-01-10 13:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('segment_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('demographic', 'Demographic'), ('activity', 'Activity'), ('risk', 'Risk'), ('value', 'Value'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('criteria', models.JSONField(default=dict)),
                ('auto_refresh', models.BooleanField(default=False)),
                ('refresh_interval', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('customer_count', models.IntegerField(default=0)),
                ('last_refresh', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Segment',
                'verbose_name_plural': 'Customer Segments',
                'db_table': 'customer_segments',
                'ordering': ['-last_refresh', '-created_at'],
            },
        ),
    ]
