# Generated by Django 5.2.6 on 2026-01-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_apps', '0003_campaign_approvaltrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='channels',
            field=models.JSONField(default=list, help_text="List of channels like ['SMS', 'Push', 'Email']"),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('incentive', 'Incentive'), ('informational', 'Informational'), ('win_back', 'Win-back'), ('info', 'Info')], max_length=20),
        ),
    ]
