# Generated by Django 5.2.6 on 2026-01-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_apps', '0004_campaign_channels_alter_campaign_campaign_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='channel_settings',
            field=models.JSONField(default=dict, help_text='Channel-specific settings'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_config',
            field=models.JSONField(blank=True, help_text='Email configuration', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='messages',
            field=models.JSONField(default=dict, help_text='Channel-specific messages'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='reward_caps',
            field=models.JSONField(default=dict, help_text='Reward caps configuration'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='selected_segment_ids',
            field=models.JSONField(default=list, help_text='List of selected segment UUIDs'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_targeted_customers',
            field=models.PositiveIntegerField(default=0, help_text='Total number of targeted customers'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='uploaded_file',
            field=models.JSONField(blank=True, help_text='Uploaded file details for custom targeting', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='frequency_cap',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('unlimited', 'Unlimited'), ('once_per_day', 'Once Per Day')], default='unlimited', max_length=20),
        ),
    ]
