from django.db import models

class AIInsightSummary(models.Model):
    """
    Powers the top-level KPI cards: High Churn Risk, Growth Opportunity, ROI.
    These are global or segment-specific aggregates generated by the AI.
    """
    segment = models.OneToOneField('CustomerSegment', on_delete=models.CASCADE, related_name='ai_summary')
    high_churn_risk_count = models.PositiveIntegerField()
    growth_opportunity_count = models.PositiveIntegerField()
    expected_roi_percent = models.DecimalField(max_digits=10, decimal_places=2) # e.g., 320.00
    last_run_date = models.DateTimeField(auto_now=True)

class AIRecommendation(models.Model):
    """
    Powers the 'Recommended Actions' cards.
    Each record represents a specific strategy identified by the AI.
    """
    class Priority(models.TextChoices):
        HIGH = 'high', 'High Priority'
        MEDIUM = 'medium', 'Medium Priority'
        LOW = 'low', 'Low Priority'

    segment = models.ForeignKey('CustomerSegment', on_delete=models.CASCADE, related_name='recommendations')
    
    # Header Info
    title = models.CharField(max_length=255) # e.g., "High Value Dormant 45 Days"
    customer_count = models.PositiveIntegerField()
    priority = models.CharField(max_length=10, choices=Priority.choices)
    churn_probability = models.FloatField() # e.g., 0.78 for 78%
    
    # The "Prescription" (Actionable Data)
    recommended_action = models.TextField() # e.g., "Win-back Campaign with 20% Bonus"
    best_channel = models.CharField(max_length=100) # e.g., "SMS + USSD Push"
    suggested_reward = models.CharField(max_length=255) # e.g., "KES 50 Cashback"
    expected_uplift_percent = models.FloatField() # e.g., 35.0 for +35%
    
    # Status
    is_converted_to_campaign = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-priority', '-expected_uplift_percent']