from django.db import models

class CustomerSegment(models.Model):
   
    name = models.CharField(max_length=255, db_index=True)
    
    
    # Configuration
    filters = models.JSONField(default=dict) 
    rule_logic = models.CharField(max_length=3, default='AND')
    status = models.CharField(max_length=20, default='Active')
    
    # State management for the UI refresh button
    is_refreshing = models.BooleanField(default=False)
    last_refresh = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Customer Segment"

class SegmentMember(models.Model):
    """
    The 'Source of Truth' generated by your rules.
    Your AI script will iterate over these records.
    """
    segment = models.ForeignKey(CustomerSegment, on_delete=models.CASCADE, related_name='members')
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    
    # We can add a 'snapshot' field if you want to store the 
    # AI result (Active/Dormant/Churn) specifically for this segment context.
    ai_label = models.CharField(max_length=20, null=True, blank=True) 
    ai_score = models.FloatField(null=True, blank=True) # e.g. Churn probability 0.85

    class Meta:
        unique_together = ('segment', 'customer')
        indexes = [
            models.Index(fields=['segment', 'ai_label']),
        ]